### ISSUE TITLE
Power Issue after some hours worktime

### ISSUE THREAD

**Issue by headhunter84** [900hasse/FS22_REAimplements#4]
With reaching 4 hours worktime harvester Grimme Ventor 4150 have no longer enough power for fieldwork. Its a nice idea if damage is high vehicles haven't longer enough power for fieldwork, but should not set to low for a restriction. Repairing harvester doesn't fix this issue. Maybe this power issue effects other harvesters to (not tested). Deactivated REAimplements was the only way to fix it.

**Comment by talianagisan** [comment]
The default game reduces power of equipment on a linear scale from 25% to 100% damage. I havent seen this with wheat harvesters on my games.

**Comment by headhunter84** [comment]
> The default game reduces power of equipment on a linear scale from 25% to 100% damage. I havent seen this with wheat harvesters on my games.

Repair doesn't fix power issue. I use all REA mods, maybe some other REA-things can effect the powerusage.  

Only details i can add: seasons active (1 day  a month), about 5 p.m. November, weather conditions 9°C dry and no water on field.

**Comment by 900hasse** [comment]
Hello!

 

I have seen your mails but have got a lot to do right now.

I will address this when things calm down a bit 😊

 

Sorry for the late response!

 

//hans

 

Från: headhunter84 ***@***.***> 
Skickat: den 6 mars 2022 11:18
Till: 900hasse/FS22_REAimplements ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: Re: [900hasse/FS22_REAimplements] Power Issue after some hours worktime (Issue #4)

 

The default game reduces power of equipment on a linear scale from 25% to 100% damage. I havent seen this with wheat harvesters on my games.

Repair doesn't fix power issue. So vehicles looses power by increasing operating hours. Loose power after only 4 hours is bad, because you can't do anything to solve this. Buying a new vehicle can't be the solution. There are only 2 ways to fix it, Giants fix it or adjust powerusage for havesters in REAimplements script.
