### ISSUE TITLE
Round Baler Extension mod conflict

### ISSUE THREAD

**Issue by cwhandersen** [900hasse/FS22_REAimplements#9]
Hi
This is not a problem with your mod per say. But I've recently download a mod called Round Baler Extension. 
But I noticed that the Round Baler Ext mod doesn't work properly. So I used like 30 - 40 minutes going through my mods trying to find out why it wasn't working as intended. 
And I've found out the it's REA Implements causing the issue.
The issue is that the Round Baler Ext mod is supposed to slow down your tractor to 8 km/h while baling, when the baler hits 90% and then come to a complete stop once it hits 100%.

Could you maybe take a look at the Round Baler Ext mod and see if you can find out why this is happening. 
Because I am really not smart enough to figure it out. And I really wanna keep using both mods.

You make absolutely fantastic mods btw. And I use them all in all my save games. Keep up the amazing work.

Link to Round Baler Extension mod:
https://www.lsfarming-mods.com/filebase/file/103-rundballenpressen-erweiterung/

**Comment by 900hasse** [comment]
Hello!

 

REA-implements forces the implement speed to be lowered when to much horsepower is added to the PTO, probably the bale mod uses the same variable to slow down the baler when the limit is reached.

 

Without looking into it I would think that these mods can’t be used together with it working as intended.

 

//Hans

 

Från: cwhandersen ***@***.***> 
Skickat: den 15 februari 2023 23:34
Till: 900hasse/FS22_REAimplements ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [900hasse/FS22_REAimplements] Round Baler Extension mod conflict (Issue #9)

 

Hi
This is not a problem with your mod per say. But I've recently download a mod called Round Baler Extension.
But I noticed that the Round Baler Ext mod doesn't work properly. So I used like 30 - 40 minutes going through my mods trying to find out why it wasn't working as intended.
And I've found out the it's REA Implements causing the issue.
The issue is that the Round Baler Ext mod is supposed to slow down your tractor to 8 km/h while baling, when the baler hits 90% and then come to a complete stop once it hits 100%.

Could you maybe take a look at the Round Baler Ext mod and see if you can find out why this is happening.
Because I am really not smart enough to figure it out. And I really wanna keep using both mods.

You make absolutely fantastic mods btw. And I use them all in all my save games. Keep up the amazing work.

Link to Round Baler Extension mod:
https://www.lsfarming-mods.com/filebase/file/103-rundballenpressen-erweiterung/

**Comment by cwhandersen** [comment]
That could be the problem.
Thanks for the help.
